apiVersion: apps/v1
kind: Deployment
metadata:
  name: json-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: json-server
  template:
    metadata:
      labels:
        app: json-server
    spec:
      containers:
      - name: json-server
        image: az400erickregistry.azurecr.io/#{imageRepositoryjsvr}:#{IMAGE_JSVR}#
        ports:
        - containerPort: 3003
